name: Java Code Style Checks and Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Code style checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
      - name: Run code style checks
        uses: mvn spotless:check

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8', '11', '17']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Run tests
        run: mvn test

  e2e-test:
    name: End-to-end tests
    runs-on: ubuntu-latest
    env:
      DISABLE_BLOCKCHAIN_EXPLORER: 1
      DISABLE_LOGSPOUT: 1
      FABRIC_ROOT: /tmp/.fabric
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
      - name: Set up Hyperledger Fabric network
        run: |
          ./tests/scripts/fabric download
          ./tests/scripts/fabric network up
          ./tests/scripts/fabric chaincode deploy
      # - name: Run tests
      #   run: go run ./tests/e2e/go/run.go
      - name: Clean up Hyperledger Fabric network
        run: |
          ./tests/scripts/fabric network down
