name: Run Code Style Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v2
